export interface Discount {
  id: number;
  productId: number;
  type: string;
  subtype: string;
  title: string;
  price: number;
  publishUp: string | null;
  publishDown: string | null;
  description: string;
  code: string;
  notice: string;
  ordering: number;
  state: boolean;
  hide: boolean;
  minPrice: number | null;
  quantity: number | null;
  timesPerUser: number | null;
  firstBuy: number | null;
  afterRegistered: number | null;
  canRollback: boolean;
  combine: string;
  combineTargets: any;
  users: any;
  categories: any;
  products: any;
  tags: any;
  payments: any;
  shippings: any;
  applyProducts: any;
  minProductQuantity: number | null;
  minCartItems: number | null;
  minCartPrice: number | null;
  freeShipping: boolean;
  method: string;
  accumulate: boolean;
  applyTo: string;
  created: string | null;
  modified: string | null;
  createdBy: number;
  modifiedBy: number;
  params: any;
  [prop: string]: any;
}
